apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnet-app
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-dotnet: "true"
      labels:
        app: dotnet-app
    spec:
      containers:
      - name: dotnet-app
        image: leocaptain/helloworldwebapp
        ports:
        - containerPort: 80