apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-spring-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-spring-app
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
      labels:
        app: java-spring-app
    spec:
      containers:
      - name: java-app
        image: leocaptain/with_spring_boot_traces
        ports:
        - containerPort: 8080