apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yaml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 5s
        static_configs:
          - targets: ['simplest-collector.default.svc.cluster.local:8889']
            
      - job_name: 'otel-collector-health-2'
        scrape_interval: 5s
        static_configs:
          - targets: ['simplest-collector-monitoring.default.svc.cluster.local:8888']
