apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-flask-app
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-python: "true"
      labels:
        app: python-flask-app
    spec:
      containers:
      - name: python-app
        image: leocaptain/with_flask_traces:latest
        ports:
        - containerPort: 5000
